Repository GOFIRST-Robotics/Lunabotics, pull requests merged in 2024-03, with the labels that each got.

#170 Gazebo competition field + drivetrain fixes
  README.md
  src/drivetrain/drivetrain/drivetrain_node.py
  src/gazebo/gazebo_files/worlds/competition_field.sdf
  src/gazebo/ros_gz_description/models/competition_field/meshes/basic_collision.stl
  src/gazebo/ros_gz_description/models/competition_field/meshes/competition_field.dae
  src/gazebo/ros_gz_description/models/competition_field/model.config
  src/gazebo/ros_gz_description/models/competition_field/model.sdf
  src/gazebo/ros_gz_description/models/master_ASM/urdf/master_ASM.urdf
  src/gazebo/ros_gz_description/models/sun/model.config
  src/gazebo/ros_gz_description/models/sun/model.sdf
  src/gazebo/ros_gz_launch/launch/competition_field.launch.py
  src/gazebo/ros_gz_launch/launch/joy_gazebo.launch.py
Labels: enhancement, new feature

#172 Deleted old apriltag code from main_control_node & Renamed conveyor to skimmer
  src/rovr_control/rovr_control/main_control_node.py
  src/skimmer/setup.py
  src/skimmer/skimmer/ros_check_load.py
Labels: bug, enhancement

#183 Calculated the KSC Field Apriltag Coordinates
  src/apriltag/apriltag/Apriltag Coordinates.txt
  src/apriltag/apriltag/apriltag_location_nasa.urdf.xarco
  src/apriltag/apriltag/apriltag_location_ucf_bot.urdf.xarco
  src/apriltag/apriltag/apriltag_location_ucf_top.urdf.xarco
Labels: enhancement

#179 Gazebo april tags and camera
  src/apriltag/apriltag/apriltag_node.py
  src/apriltag/launch/apriltag_launch.py
  src/apriltag/launch/apriltag_no_zed_launch.py
  src/gazebo/gazebo_files/worlds/competition_field.sdf
  src/gazebo/ros_gz_description/models/Apriltag36_11_00000/materials/meshes/apriltag.dae
  src/gazebo/ros_gz_description/models/Apriltag36_11_00000/materials/textures/tag36_11_00000.png
  src/gazebo/ros_gz_description/models/Apriltag36_11_00000/model.config
  src/gazebo/ros_gz_description/models/Apriltag36_11_00000/model.sdf
  src/gazebo/ros_gz_description/models/Apriltag36_11_00001/materials/meshes/apriltag.dae
  src/gazebo/ros_gz_description/models/Apriltag36_11_00001/materials/textures/tag36_11_00001.png
  src/gazebo/ros_gz_description/models/Apriltag36_11_00001/model.config
  src/gazebo/ros_gz_description/models/Apriltag36_11_00001/model.sdf
  src/gazebo/ros_gz_description/models/Apriltag36_11_00002/materials/meshes/apriltag.dae
  src/gazebo/ros_gz_description/models/Apriltag36_11_00002/materials/textures/tag36_11_00002.png
  src/gazebo/ros_gz_description/models/Apriltag36_11_00002/model.config
  src/gazebo/ros_gz_description/models/Apriltag36_11_00002/model.sdf
  src/gazebo/ros_gz_description/models/Apriltag36_11_00003/materials/meshes/apriltag.dae
  src/gazebo/ros_gz_description/models/Apriltag36_11_00003/materials/textures/tag36_11_00003.png
  src/gazebo/ros_gz_description/models/Apriltag36_11_00003/model.config
  src/gazebo/ros_gz_description/models/Apriltag36_11_00003/model.sdf
  src/gazebo/ros_gz_description/models/Apriltag36_11_00004/materials/meshes/apriltag.dae
  src/gazebo/ros_gz_description/models/Apriltag36_11_00004/materials/textures/tag36_11_00004.png
  src/gazebo/ros_gz_description/models/Apriltag36_11_00004/model.config
  src/gazebo/ros_gz_description/models/Apriltag36_11_00004/model.sdf
  src/gazebo/ros_gz_description/models/Apriltag36_11_00005/materials/meshes/apriltag.dae
  src/gazebo/ros_gz_description/models/Apriltag36_11_00005/materials/textures/tag36_11_00005.png
  src/gazebo/ros_gz_description/models/Apriltag36_11_00005/model.config
  src/gazebo/ros_gz_description/models/Apriltag36_11_00005/model.sdf
  src/gazebo/ros_gz_description/models/competition_field/meshes/basic_collision.stl
  src/gazebo/ros_gz_description/models/competition_field/meshes/competition_field.dae
  src/gazebo/ros_gz_description/models/competition_field/model.sdf
  src/gazebo/ros_gz_description/models/ground/ground.sdf
  src/gazebo/ros_gz_description/models/ground/model.config
  src/gazebo/ros_gz_description/models/master_ASM/urdf/master_ASM.urdf
  src/gazebo/ros_gz_launch/config/camera.rviz
  src/gazebo/ros_gz_launch/config/ros_gz_bridge.yaml
  src/gazebo/ros_gz_launch/launch/competition_field.launch.py
  src/gazebo/ros_gz_launch/launch/joy_gazebo.launch.py
  src/rovr_control/rovr_control/main_control_node.py
Labels: new feature

#167 Merge the "URDF" branch into main (finally!)
  README.md
  config/nav2_isaac_sim.yaml
  config/rviz/zed_example.rviz
  config/urdf/robot_descr.urdf.xarco
  src/gazebo/ros_gz_description/models/master_ASM/meshes/zed2i.stl
  src/gazebo/ros_gz_description/models/master_ASM/urdf/master_ASM.urdf
  src/isaac_ros/isaac_ros_launch/launch/apriltag_launch.py
  src/isaac_ros/isaac_ros_launch/launch/nav2_launch.py
  src/isaac_ros/isaac_ros_launch/launch/nvblox.launch.py
  src/isaac_ros/isaac_ros_launch/launch/rviz.launch.py
  src/isaac_ros/isaac_ros_launch/launch/zed2i.launch.py
Labels: enhancement, new feature

#186 Changed Nav2 footprint from a circle to a rectangle
  config/nav2_isaac_sim.yaml
Labels: enhancement
