Repository GOFIRST-Robotics/Lunabotics, pull requests merged in 2024-04, with the labels that each got.

#190 (DRAFT) Drivetrain Testing Improvements (NOT READY YET)I
  config/drivetrain_config.yaml
  config/motor_control.yaml
  config/rovr_control.yaml
  src/drivetrain/drivetrain/drivetrain_node.py
  src/motor_control/src/motor_control_node.cpp
  src/rovr_control/launch/main_launch.py
  src/rovr_control/launch/main_no_joysticks_launch.py
  src/rovr_control/rovr_control/read_serial.py
  src/skimmer/skimmer/skimmer_node.py
Labels: bug, enhancement

#195 Fixed ZED TFs for both Gazebo & RVIZ
  config/sensors/camera_info.yaml
  config/sensors/zed2i.yaml
  config/sensors/zed_common.yaml
  config/urdf/robot_descr.urdf.xarco
  src/gazebo/ros_gz_description/models/master_ASM/urdf/master_ASM.urdf
Labels: enhancement

#192 Fixed the absolute encoder code
  config/drivetrain_config.yaml
  src/drivetrain/drivetrain/drivetrain_node.py
  src/rovr_control/rovr_control/read_serial.py
Labels: bug

#200 NASA KSC field added in Gazebo
  README.md
  src/apriltag/apriltag/Apriltag Coordinates.txt
  src/apriltag/apriltag/apriltag_location_nasa.urdf.xarco
  src/gazebo/gazebo_files/worlds/NASA_field.sdf
  src/gazebo/gazebo_files/worlds/UCF_field.sdf
  src/gazebo/ros_gz_description/models/NASA_field/meshes/NASA_basic.stl
  src/gazebo/ros_gz_description/models/NASA_field/meshes/NASA_field.dae
  src/gazebo/ros_gz_description/models/NASA_field/model.config
  src/gazebo/ros_gz_description/models/NASA_field/model.sdf
  src/gazebo/ros_gz_description/models/UCF_field/meshes/UCF_basic.stl
  src/gazebo/ros_gz_description/models/UCF_field/meshes/UCF_field.dae
  src/gazebo/ros_gz_description/models/UCF_field/model.config
  src/gazebo/ros_gz_description/models/UCF_field/model.sdf
  src/gazebo/ros_gz_launch/launch/NASA_field.launch.py
  src/gazebo/ros_gz_launch/launch/UCF_field.launch.py
  src/gazebo/ros_gz_launch/launch/joy_gazebo.launch.py
Labels: enhancement, new feature

#215 Nav2 works with Gazebo!
  src/gazebo/gazebo_files/worlds/NASA_field.sdf
  src/gazebo/gazebo_files/worlds/UCF_field.sdf
  src/gazebo/ros_gz_launch/config/camera.rviz
  src/gazebo/ros_gz_launch/config/ros_gz_bridge.yaml
  src/isaac_ros/isaac_ros_launch/launch/nav2_gazebo_launch.py
  src/isaac_ros/isaac_ros_launch/launch/nvblox.launch.py
  src/robot_description/models/master_ASM/urdf/master_ASM.urdf
  src/robot_description/models/master_ASM/urdf/master_ASM.urdf.xacro
Labels: enhancement, new feature

#201 Absolute Encoders Fix!
  config/drivetrain_config.yaml
  src/drivetrain/drivetrain/drivetrain_node.py
  src/rovr_control/launch/main_launch.py
  src/rovr_control/launch/main_no_joysticks_launch.py
  src/rovr_control/package.xml
Labels: bug

#219 Created a launch file for the operator laptop
  scripts/enter_isaac_ros_container.sh
  scripts/laptop.sh
  src/gstreamer/launch/laptop_launch.py
  src/gstreamer/package.xml
  src/gstreamer/setup.py
Labels: enhancement

#207 Testing odom reset with Apriltags - it works now!
  config/rovr_control.yaml
  src/apriltag/apriltag/apriltag_node.py
  src/apriltag/launch/apriltag_gazebo_launch.py
  src/gazebo/gazebo_files/worlds/UCF_field.sdf
  src/isaac_ros/isaac_ros_launch/launch/gazebo_launch.py
  src/isaac_ros/isaac_ros_launch/launch/isaac_launch.py
  src/robot_description/models/master_ASM/urdf/master_ASM.urdf.xacro
  src/rovr_control/rovr_control/main_control_node.py
Labels: bug, enhancement

#226 Record svo file from the zed launch file
  config/sensors/zed_common.yaml
  src/isaac_ros/isaac_ros_launch/launch/zed2i.launch.py
Labels: new feature
