Repository GOFIRST-Robotics/Lunabotics, pull requests merged in 2024-11, with the labels that each got.

#310 Implemented requirements for the drivetrain subsystem
  config/drivetrain_config.yaml
  src/drivetrain/drivetrain/drivetrain_node.py
Labels: enhancement

#319 Cool startup script changes
  docker/README.md
  scripts/build_image.sh
  scripts/enter_isaac_ros_container.sh
Labels: enhancement

#325 Default our Simulation to the NASA field
  src/apriltag/apriltag/apriltag_location_nasa.urdf.xarco
  src/apriltag/apriltag/apriltag_location_ucf_bot.urdf.xarco
  src/apriltag/apriltag/apriltag_location_ucf_top.urdf.xarco
  src/gazebo/ros_gz_description/models/NASA_field/model.sdf
  src/gazebo/ros_gz_description/models/UCF_field/model.sdf
  src/isaac_ros/isaac_ros_launch/launch/isaac_launch.py
Labels: bug

#327 Make a Service for motor ramp up/down
  src/motor_control/src/motor_control_node.cpp
  src/rovr_interfaces/srv/MotorCommandSet.srv
Labels: enhancement, new feature
