Repository GOFIRST-Robotics/Lunabotics, pull requests merged in 2024-05, with the labels that each got.

#230 Testing lift position control
  config/rovr_control.yaml
  src/motor_control/src/motor_control_node.cpp
  src/rovr_control/rovr_control/main_control_node.py
  src/rovr_interfaces/CMakeLists.txt
  src/rovr_interfaces/srv/SetHeight.srv
  src/rovr_interfaces/srv/SetPosition.srv
  src/skimmer/skimmer/ros_check_load.py
  src/skimmer/skimmer/skimmer_node.py
Labels: enhancement

#168 Created an "everything" launch file to start every node we need on the robot
  scripts/launch_everything.sh
  src/isaac_ros/isaac_ros_launch/launch/EVERYTHING_launch.py
  src/motor_control/src/motor_control_node.cpp
Labels: setup, new feature

#193 Create a gstreamer application to stream compressed video streams
  README.md
  scripts/enter_isaac_ros_container.sh
  scripts/laptop.sh
  src/gstreamer/LICENSE
  src/gstreamer/gstreamer/__init__.py
  src/gstreamer/gstreamer/client.py
  src/gstreamer/gstreamer/client_gstreamer.py
  src/gstreamer/gstreamer/client_main.py
  src/gstreamer/gstreamer/client_widget.py
  src/gstreamer/gstreamer/server_gstreamer.py
  src/gstreamer/gstreamer/server_node.py
  src/gstreamer/launch/laptop_launch.py
  src/gstreamer/package.xml
  src/gstreamer/plugin.xml
  src/gstreamer/resource/gstreamer
  src/gstreamer/resource/gstreamer-select.ui
  src/gstreamer/setup.cfg
  src/gstreamer/setup.py
  src/gstreamer/test/test_copyright.py
  src/gstreamer/test/test_flake8.py
  src/gstreamer/test/test_pep257.py
  src/rovr_interfaces/CMakeLists.txt
  src/rovr_interfaces/srv/SetActiveCamera.srv
  src/rovr_interfaces/srv/SetClientIp.srv
  src/rovr_interfaces/srv/SetEncoding.srv
Labels: new feature

#246 Gazebo and Auto fixes during the competition + some cleanup after
  config/nav2_isaac_sim.yaml
  config/nvblox/nvblox_base.yaml
  src/apriltag/apriltag/apriltag_node.py
  src/gazebo/gazebo_files/worlds/UCF_field.sdf
  src/gstreamer/launch/laptop_launch.py
  src/isaac_ros/isaac_ros_launch/launch/isaac_launch.py
  src/isaac_ros/isaac_ros_launch/launch/nvblox.launch.py
  src/isaac_ros/isaac_ros_launch/launch/rviz.launch.py
  src/rovr_control/rovr_control/costmap_2d.py
  src/rovr_control/rovr_control/main_control_node.py
Labels: bug

#248 Utilize PathJoinSubstitution
  src/gazebo/ros_gz_launch/launch/NASA_field.launch.py
  src/gazebo/ros_gz_launch/launch/UCF_field.launch.py
  src/gazebo/ros_gz_launch/launch/joy_gazebo.launch.py
  src/gstreamer/launch/laptop_launch.py
  src/isaac_ros/isaac_ros_launch/launch/EVERYTHING_launch.py
  src/isaac_ros/isaac_ros_launch/launch/gazebo_launch.py
  src/isaac_ros/isaac_ros_launch/launch/isaac_launch.py
  src/isaac_ros/isaac_ros_launch/launch/nvblox.launch.py
  src/isaac_ros/isaac_ros_launch/launch/rviz.launch.py
  src/isaac_ros/isaac_ros_launch/launch/zed2i.launch.py
  src/robot_description/launch/robot_description.launch.py
Labels: enhancement

#249 Added a joint state publisher to visualize the robot wheels in RVIZ
  src/gazebo/ros_gz_launch/config/ros_gz_bridge.yaml
  src/gazebo/ros_gz_launch/launch/NASA_field.launch.py
  src/gazebo/ros_gz_launch/launch/UCF_field.launch.py
  src/isaac_ros/isaac_ros_launch/launch/zed2i.launch.py
  src/robot_description/launch/robot_description.launch.py
  src/robot_description/models/master_ASM/urdf/master_ASM.urdf.xacro
Labels: new feature

#250 Readme Cleanup (including the addition of a more maintainable diagram)
  README.md
  assets/NASA-Lunabotics-Software-Diagram.png
Labels: enhancement
